// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebtufiefalvzuuqoaxhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVidHVmaWVmYWx2enV1cW9heGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDQxMjIsImV4cCI6MjA2OTMyMDEyMn0.U0VPa2TJzt9fNJAnSMFMmxJB-rnzKoUpa1Z31oM9jug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});